# Generated by Django 5.2 on 2025-04-07 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='producto',
            new_name='productos',
        ),
    ]
